

export const theme = {
	MdSysColorPrimary: "#6f49af",
	MdSysColorOnPrimary: "#ffffff",
	MdSysColorPrimaryContainer: "#eddcff",
	MdSysColorOnPrimaryContainer: "#260059",
	MdSysColorSecondary: "#635a70",
	MdSysColorOnSecondary: "#ffffff",
	MdSysColorSecondaryContainer: "#eadef7",
	MdSysColorOnSecondaryContainer: "#1f182b",
	MdSysColorTertiary: "#7f515c",
	MdSysColorOnTertiary: "#ffffff",
	MdSysColorTertiaryContainer: "#ffd9e1",
	MdSysColorOnTertiaryContainer: "#32101a",
	MdSysColorError: "#ba1b1b",
	MdSysColorErrorContainer: "#ffdad4",
	MdSysColorOnError: "#ffffff",
	MdSysColorOnErrorContainer: "#410001",
	MdSysColorBackground: "#fffbfc",
	MdSysColorOnBackground: "#1d1b1e",
	MdSysColorSurface: "#fffbfc",
	MdSysColorOnSurface: "#1d1b1e",
	MdSysColorSurfaceVariant: "#e8e0eb",
	MdSysColorOnSurfaceVariant: "#49454e",
	MdSysColorOutline: "#7a757e",
	MdSysColorInverseOnSurface: "#f5eff4",
	MdSysColorInverseSurface: "#323033",
	MdSysColorInversePrimary: "#d6baff",
	MdSysColorShadow: "#000000",
	MdSysColorPrimaryLight: "#6f49af",
	MdSysColorOnPrimaryLight: "#ffffff",
	MdSysColorPrimaryContainerLight: "#eddcff",
	MdSysColorOnPrimaryContainerLight: "#260059",
	MdSysColorSecondaryLight: "#635a70",
	MdSysColorOnSecondaryLight: "#ffffff",
	MdSysColorSecondaryContainerLight: "#eadef7",
	MdSysColorOnSecondaryContainerLight: "#1f182b",
	MdSysColorTertiaryLight: "#7f515c",
	MdSysColorOnTertiaryLight: "#ffffff",
	MdSysColorTertiaryContainerLight: "#ffd9e1",
	MdSysColorOnTertiaryContainerLight: "#32101a",
	MdSysColorErrorLight: "#ba1b1b",
	MdSysColorErrorContainerLight: "#ffdad4",
	MdSysColorOnErrorLight: "#ffffff",
	MdSysColorOnErrorContainerLight: "#410001",
	MdSysColorBackgroundLight: "#fffbfc",
	MdSysColorOnBackgroundLight: "#1d1b1e",
	MdSysColorSurfaceLight: "#fffbfc",
	MdSysColorOnSurfaceLight: "#1d1b1e",
	MdSysColorSurfaceVariantLight: "#e8e0eb",
	MdSysColorOnSurfaceVariantLight: "#49454e",
	MdSysColorOutlineLight: "#7a757e",
	MdSysColorInverseOnSurfaceLight: "#f5eff4",
	MdSysColorInverseSurfaceLight: "#323033",
	MdSysColorInversePrimaryLight: "#d6baff",
	MdSysColorShadowLight: "#000000",
	MdSysColorPrimaryDark: "#d6baff",
	MdSysColorOnPrimaryDark: "#3f127d",
	MdSysColorPrimaryContainerDark: "#562f95",
	MdSysColorOnPrimaryContainerDark: "#eddcff",
	MdSysColorSecondaryDark: "#cec2db",
	MdSysColorOnSecondaryDark: "#342d40",
	MdSysColorSecondaryContainerDark: "#4b4358",
	MdSysColorOnSecondaryContainerDark: "#eadef7",
	MdSysColorTertiaryDark: "#f1b8c4",
	MdSysColorOnTertiaryDark: "#4a252f",
	MdSysColorTertiaryContainerDark: "#643b45",
	MdSysColorOnTertiaryContainerDark: "#ffd9e1",
	MdSysColorErrorDark: "#ffb4a9",
	MdSysColorErrorContainerDark: "#930006",
	MdSysColorOnErrorDark: "#680003",
	MdSysColorOnErrorContainerDark: "#ffdad4",
	MdSysColorBackgroundDark: "#1d1b1e",
	MdSysColorOnBackgroundDark: "#e7e1e6",
	MdSysColorSurfaceDark: "#1d1b1e",
	MdSysColorOnSurfaceDark: "#e7e1e6",
	MdSysColorSurfaceVariantDark: "#49454e",
	MdSysColorOnSurfaceVariantDark: "#cbc4cf",
	MdSysColorOutlineDark: "#958f99",
	MdSysColorInverseOnSurfaceDark: "#1d1b1e",
	MdSysColorInverseSurfaceDark: "#e7e1e6",
	MdSysColorInversePrimaryDark: "#6f49af",
	MdSysColorShadowDark: "#000000",
	MdRefPalettePrimary100: "#ffffff",
	MdRefPalettePrimary99: "#fffbfc",
	MdRefPalettePrimary95: "#f8ecff",
	MdRefPalettePrimary90: "#eddcff",
	MdRefPalettePrimary80: "#d6baff",
	MdRefPalettePrimary70: "#bf98ff",
	MdRefPalettePrimary60: "#a37ce6",
	MdRefPalettePrimary50: "#8963ca",
	MdRefPalettePrimary40: "#6f49af",
	MdRefPalettePrimary30: "#562f95",
	MdRefPalettePrimary20: "#3f127d",
	MdRefPalettePrimary10: "#260059",
	MdRefPalettePrimary0: "#000000",
	MdRefPaletteSecondary100: "#ffffff",
	MdRefPaletteSecondary99: "#fffbfc",
	MdRefPaletteSecondary95: "#f8ecff",
	MdRefPaletteSecondary90: "#eadef7",
	MdRefPaletteSecondary80: "#cec2db",
	MdRefPaletteSecondary70: "#b2a7bf",
	MdRefPaletteSecondary60: "#978da4",
	MdRefPaletteSecondary50: "#7c7389",
	MdRefPaletteSecondary40: "#635a70",
	MdRefPaletteSecondary30: "#4b4358",
	MdRefPaletteSecondary20: "#342d40",
	MdRefPaletteSecondary10: "#1f182b",
	MdRefPaletteSecondary0: "#000000",
	MdRefPaletteTertiary100: "#ffffff",
	MdRefPaletteTertiary99: "#fcfcfc",
	MdRefPaletteTertiary95: "#ffecf0",
	MdRefPaletteTertiary90: "#ffd9e1",
	MdRefPaletteTertiary80: "#f1b8c4",
	MdRefPaletteTertiary70: "#d39da9",
	MdRefPaletteTertiary60: "#b6838e",
	MdRefPaletteTertiary50: "#9a6a75",
	MdRefPaletteTertiary40: "#7f515c",
	MdRefPaletteTertiary30: "#643b45",
	MdRefPaletteTertiary20: "#4a252f",
	MdRefPaletteTertiary10: "#32101a",
	MdRefPaletteTertiary0: "#000000",
	MdRefPaletteNeutral100: "#ffffff",
	MdRefPaletteNeutral99: "#fffbfc",
	MdRefPaletteNeutral95: "#f5eff4",
	MdRefPaletteNeutral90: "#e7e1e6",
	MdRefPaletteNeutral80: "#cac5c9",
	MdRefPaletteNeutral70: "#afaaaf",
	MdRefPaletteNeutral60: "#938f93",
	MdRefPaletteNeutral50: "#79767a",
	MdRefPaletteNeutral40: "#605d61",
	MdRefPaletteNeutral30: "#49464a",
	MdRefPaletteNeutral20: "#323033",
	MdRefPaletteNeutral10: "#1d1b1e",
	MdRefPaletteNeutral0: "#000000",
	MdRefPaletteNeutralVariant100: "#ffffff",
	MdRefPaletteNeutralVariant99: "#fffbfc",
	MdRefPaletteNeutralVariant95: "#f6eef9",
	MdRefPaletteNeutralVariant90: "#e8e0eb",
	MdRefPaletteNeutralVariant80: "#cbc4cf",
	MdRefPaletteNeutralVariant70: "#b0a9b4",
	MdRefPaletteNeutralVariant60: "#958f99",
	MdRefPaletteNeutralVariant50: "#7a757e",
	MdRefPaletteNeutralVariant40: "#615c66",
	MdRefPaletteNeutralVariant30: "#49454e",
	MdRefPaletteNeutralVariant20: "#332f37",
	MdRefPaletteNeutralVariant10: "#1d1a22",
	MdRefPaletteNeutralVariant0: "#000000",
	MdRefPaletteError100: "#ffffff",
	MdRefPaletteError99: "#fcfcfc",
	MdRefPaletteError95: "#ffede9",
	MdRefPaletteError90: "#ffdad4",
	MdRefPaletteError80: "#ffb4a9",
	MdRefPaletteError70: "#ff897a",
	MdRefPaletteError60: "#ff5449",
	MdRefPaletteError50: "#dd3730",
	MdRefPaletteError40: "#ba1b1b",
	MdRefPaletteError30: "#930006",
	MdRefPaletteError20: "#680003",
	MdRefPaletteError10: "#410001",
	MdRefPaletteError0: "#000000",
	MdSysTypescaleDisplay1Family: "Titillium Web",
	MdSysTypescaleDisplay1Weight: 400,
	MdSysTypescaleDisplayLargeFamily: "Titillium Web",
	MdSysTypescaleDisplayLargeWeight: 400,
	MdSysTypescaleDisplayMediumFamily: "Titillium Web",
	MdSysTypescaleDisplayMediumWeight: 400,
	MdSysTypescaleDisplaySmallFamily: "Titillium Web",
	MdSysTypescaleDisplaySmallWeight: 400,
	MdSysTypescaleHeadlineLargeFamily: "Titillium Web",
	MdSysTypescaleHeadlineLargeWeight: 400,
	MdSysTypescaleHeadlineMediumFamily: "Titillium Web",
	MdSysTypescaleHeadlineMediumWeight: 400,
	MdSysTypescaleHeadlineSmallFamily: "Titillium Web",
	MdSysTypescaleHeadlineSmallWeight: 400,
	MdSysTypescaleTitleLargeFamily: "Titillium Web",
	MdSysTypescaleTitleLargeWeight: 400,
	MdSysTypescaleHeadline6Family: "Titillium Web",
	MdSysTypescaleHeadline6Weight: 400,
	MdSysTypescaleTitleMediumFamily: "Titillium Web",
	MdSysTypescaleTitleMediumWeight: 600,
	MdSysTypescaleTitleSmallFamily: "Titillium Web",
	MdSysTypescaleTitleSmallWeight: 600,
	MdSysTypescaleLabelLargeFamily: "Titillium Web",
	MdSysTypescaleLabelLargeWeight: 600,
	MdSysTypescaleBodyLargeFamily: "Titillium Web",
	MdSysTypescaleBodyLargeWeight: 400,
	MdSysTypescaleBodyMediumFamily: "Titillium Web",
	MdSysTypescaleBodyMediumWeight: 400,
	MdSysTypescaleBodySmallFamily: "Titillium Web",
	MdSysTypescaleBodySmallWeight: 400,
	MdSysTypescaleLabelMediumFamily: "Titillium Web",
	MdSysTypescaleLabelMediumWeight: 600,
	MdSysTypescaleLabelSmallFamily: "Titillium Web",
	MdSysTypescaleLabelSmallWeight: 600,
	MdSysTypescaleDisplay1Size: "64px",
	MdSysTypescaleDisplayLargeSize: "57px",
	MdSysTypescaleDisplayMediumSize: "45px",
	MdSysTypescaleDisplaySmallSize: "36px",
	MdSysTypescaleHeadlineLargeSize: "32px",
	MdSysTypescaleHeadlineMediumSize: "28px",
	MdSysTypescaleHeadlineSmallSize: "24px",
	MdSysTypescaleTitleLargeSize: "22px",
	MdSysTypescaleHeadline6Size: "18px",
	MdSysTypescaleTitleMediumSize: "16px",
	MdSysTypescaleTitleSmallSize: "14px",
	MdSysTypescaleLabelLargeSize: "14px",
	MdSysTypescaleBodyLargeSize: "16px",
	MdSysTypescaleBodyMediumSize: "14px",
	MdSysTypescaleBodySmallSize: "12px",
	MdSysTypescaleLabelMediumSize: "12px",
	MdSysTypescaleLabelSmallSize: "11px",
	/** ------ */

	MdSysColorSurface1: '#F8F2F8',
	MdSysColorSurface2: '#F3EDF6',
	MdSysColorSurface3: '#EFE7F4',
	MdSysColorSurface4: '#EEE6F3',
	MdSysColorSurface5: '#EBE2F1',

	
}
